### ISSUE TITLE
Buffer

### ISSUE THREAD

**Issue by jhollist** [ropensci/lawn#1]
See you couldn't wait to work on this one, @sckott!  

I've been wanting to dig into the json, geojson, and V8 stuff so I started messing around with it.  I think I have a wrapper for the buffer (which has some issues).  

If you are are interested, I can push that and submit a PR.  Will also add an example to README, if you'd like.

**Comment by sckott** [comment]
hey jeff, yeah, i didn't see any excitement for this topic in the unconf repo (As there was for other ideas), and I don't think the morgan herlocker of turf.js is going to be there, so decided to just go for it. 

yeah, sounds good on PR. do you mean `buffer` from turf.js?

**Comment by jhollist** [comment]
yep. `buffer` from turf

Soemthing funky with how turf.js is doing the buffer though.  

Once I get kids in bed, I'll submit the PR.

**Comment by sckott** [comment]
cool!

**Comment by jhollist** [comment]
Just submitted.  Also working up an example of the weirdness in buffer.  May submit an issue over there.

**Comment by jhollist** [comment]
So here's the issue.  The buffer of a point should be, in theory, a circle. The buffer from rgeos::gBuffer is in green, from lawn::buffer (thus turf.js) is in red.  Same point used for both with a 100 meter buffer.  

![buff prob](http://jwhollister.com/public/files/Rplot02.png)

**Comment by sckott** [comment]
That does seem bad, can you share the code to reproduce that?

**Comment by jhollist** [comment]
Sure can.  Its on a separate branch that I haven't pushed yet.  Can get to
it tonight or tomorrow.

**Comment by jhollist** [comment]
@sckott, I took a different tact and put together a gist.  It is at https://gist.github.com/jhollist/9dda43e9fdbf7b24ebb2

The issue is scale related.  You can see the smaller distances don't result in circles.  I also wanted to avoid doing too much to the resultant objects just to make sure something else wasn't going on.  These are just buffers written out to geojson files.

I am pretty sure this is something going on with the turf.buffer.js

**Comment by sckott** [comment]
thanks @jhollist !

Did you already open an issue with `turf.js` ?

**Comment by jhollist** [comment]
Not yet.  I wanted to make sure it was a turf thing and not something boneheaded that I have done.

**Comment by jhollist** [comment]
Well, not sure I should open that issue...  [jsfiddle looks fine](http://jsfiddle.net/jhollist/MHYRt/26/).

Bah!!!!

**Comment by jhollist** [comment]
You think it could be a precision thing?

**Comment by sckott** [comment]
hmmm, maybe, i'll take a look at the internals and see if we're dropping digits

**Comment by jhollist** [comment]
I just upped my digits with `options(digits=22)` and get the all those digits returned with `buffer`.

**Comment by sckott** [comment]
@jhollist hmmm, i used your gist eg., the 100 meter buffer one, and converted the sp class stuff back to geojson and plotted https://gist.github.com/sckott/7a7147ec2281e081a966 

seems that they both aren't round. but the one created via `writeOGR()` is round https://gist.github.com/sckott/7a7147ec2281e081a966

so major different i think is losing significant digits maybe

looking into geojsonio to see if it can be ffixed

**Comment by sckott** [comment]
@jhollist okay, try reinstalling `lawn` and `geojsonio`

see https://gist.github.com/sckott/11fe681644086f0a789f

`jsonlite::toJSON()` was dropping digits, and can be changed with `digits` param, which I did, should be more accurate now

**Comment by sckott** [comment]
@jhollist let me know if that solves the problem

**Comment by jhollist** [comment]
scott, working on it now... Will let you know shortly.

**Comment by jhollist** [comment]
@sckott Looks good!

**Comment by sckott** [comment]
@jhollist great!

**Comment by sckott** [comment]
closing, open again @jhollist  if needed

**Comment by jhollist** [comment]
sounds good!

On Sat, Mar 7, 2015 at 3:37 PM, Scott Chamberlain <notifications@github.com>
wrote:

> closing, open again @jhollist <https://github.com/jhollist> if needed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/lawn/issues/1#issuecomment-77708822>.
>



-- 
Jeff W. Hollister
email: jeff.w.hollister@gmail.com
google voice: 401 326 2531
cell: 401 556 4087
