### ISSUE TITLE
Include proj.js in this pkg?

### ISSUE THREAD

**Issue by sckott** [ropensci/lawn#15]
@jhollist i wrapped [proj4.js](https://github.com/proj4js/proj4js) in a separate pkg https://github.com/ropensci/proj but maybe we should just include it in this pkg?  to allow easier projections?  It's pretty small, there's only one function https://github.com/ropensci/proj/blob/master/R/project.R

**Comment by jhollist** [comment]
@sckott I guess it depends on what the goal is for `lawn`.  Just a turf.js wrapper or a more broad javascript based geospatial engine for R.   The later may be a bit more compelling and including proj4.js and geojson-random.js makes sense.

**Comment by sckott** [comment]
@jhollist right, I don't have a strong feeling on this right now. Seems that projections are so important that we want to make it easy to change projections, right?  And the random.js thing was just b/c it's a small js library and does things turf doesn't do  -  Seems we can play it be ear how much goes here. Definitely don't want to make it too bloated, but having a few bells and whistles seems worth it?

**Comment by jhollist** [comment]
:+1:
