### ISSUE TITLE
Add prefix to all functions?

### ISSUE THREAD

**Issue by sckott** [ropensci/lawn#20]
There are a lot of functions that conflict with base R functions (e.g,. sum, variance, mean, min, simplify, sample, random, etc.)

we may need to add a prefix. Ideas:

* `l_`
* `lw_`
* `lwn_`
* `lawn_`

**Comment by jhollist** [comment]
:+1: 

I don't have a strong preference for any.  Slight preference for lawn_.  Don't like l_ too short and without context would be hard to decipher (is it some sort of list function?).

**Comment by sckott** [comment]
yeah, `l_` isn't great. `lawn_` probably makes the most sense. can change to that and see how we like it, can always change again before cran push
