### ISSUE TITLE
lists in union and intersect ?

### ISSUE THREAD

**Issue by sckott** [ropensci/lawn#34]
@jhollist applies to `lawn_union` and `lawn_intersect`

curious what use case this is https://github.com/ropensci/lawn/blob/master/R/union.R#L71 for when a list is passed in and you go that route with the `if` statement. Is there an example we can  use to test this?  What kind of list? Cause we can have a list of a single polygon or of many polygons, or something else

**Comment by jhollist** [comment]
@sckott Good question...

I'll try to figure out what I was thinking.  My guess is that I wanted to handle passage of a feature collection (i.e. union or intersect between multiple polygons, not just two), but it seems like turf would handle that on it's own.  I may have more sitting in my fork that explains my thinking.  I'll take a look in the next couple of days.

**Comment by sckott** [comment]
thanks @jhollist

**Comment by jhollist** [comment]
@sckott I think I tracked it down.  When I wrote those I followed your examples.  At that time only a few had been done and the object was returned to R via `ct$get` which was a list.  When I started on `intersect`, I used the results of buffer as input for my examples and without the hacky `if/then` checking for list, it would bomb.  

Since you now have `buffer`, `intersect`, and `union` returning a polygon,fc etc. it works without that check.  So, I *think* we could simply drop those `if/then` statements entirely as the input probably won't ever be a list.

**Comment by sckott** [comment]
Okay, sounds good. Well, I guess there can be list input, but our helper function `convert()` takes care of that before passing to turf

**Comment by sckott** [comment]
i can take care of it...

**Comment by sckott** [comment]
ahh, i see the problem. `lawn_buffer()` outputs a featurecollection, which is a list with a class of `featurecollection` attached, so it does get caught in that `if` statement and converted successfully to a `feature` which is what intersect or union need 

I haven't been supporting conversion from featurecollection the appropriate thing needed in a fxn, but we could make a general helper fxn to convert from featurecollection to feature, could be useful for users

**Comment by sckott** [comment]
@jhollist okay, if you have time, reinstall and try these fxns again.  The previous iteration did work, but I think the change is an improvement. But maybe it's not? thoughts

**Comment by jhollist** [comment]
@sckott I think it is an improvement.  One question...  turf.js union accepts polygon or multipolygon.  I don't have time today to play with this, but we should probably test that multipolygon's get passed correctly.  the `multipoly` in lawn_data is not a MultiPolygon (I was/am still learning geojson) it is a feature collection.  Be good to add two example MultiPolygons and test with union, intersect, etc.

**Comment by sckott** [comment]
@jhollist 

> the multipoly in lawn_data is not a MultiPolygon

thanks for pointing that out! I'll fix it

But http://turfjs.org/static/docs/module-turf_intersect.html says returns a polygon or multilinestring (and union http://turfjs.org/static/docs/module-turf_union.html returns polygon or multipolygon) - but both appear to only accept a `Polygon` object. Or am i reading it wrong.

**Comment by jhollist** [comment]
@sckott,  Wow, I am getting sloppy.  What I get for reading after kids in bed (and wine)...

You are right, I saw the return line and it didn't compute.  I think I would like these functions to take work with multiple polygons...  Turf works differently with these than the esri and geos(I think) functions.

So, I amend my prior comment and the new versions look good!

**Comment by sckott** [comment]
Okay, thanks. Closing this then. We could put in a request with turf folks to change behavior of these functions?

**Comment by jhollist** [comment]
Would be nice if you could pass multiple polygons and get the union/intersect of those.  The single polygon use case seems kind of limited.

**Comment by sckott** [comment]
agree, would be good to have more flexibility
