### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by samuelleach** [ropensci/lawn#37]
Hello.
I was just trying to scope out this package but was getting the following installation error (shown below) for the command `devtools::install_github("ropensci/lawn")`

For info `name -a` (my setup) gives:

`Darwin aquamarine.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64`

> devtools::install_github("ropensci/lawn")
Downloading github repo ropensci/lawn@master
Installing lawn
Installing 1 packages: V8
trying URL 'http://cran.rstudio.com/src/contrib/V8_0.6.tar.gz'
Content type 'application/x-gzip' length 110013 bytes (107 KB)
==================================================
downloaded 107 KB

* installing *source* package ‘V8’ ...
** package ‘V8’ successfully unpacked and MD5 sums checked
libv8 gem found in /Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.7-x86_64-darwin-14
** libs
clang++ -I/usr/local/Cellar/r/3.2.0_1/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I"/usr/local/Cellar/r/3.2.0_1/R.framework/Versions/3.2/Resources/library/Rcpp/include"  -I/Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.7-x86_64-darwin-14/vendor/v8/include -fPIC  -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -I/usr/local/Cellar/r/3.2.0_1/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I"/usr/local/Cellar/r/3.2.0_1/R.framework/Versions/3.2/Resources/library/Rcpp/include"  -I/Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.7-x86_64-darwin-14/vendor/v8/include -fPIC  -g -O2  -c V8.cpp -o V8.o
clang++ -I/usr/local/Cellar/r/3.2.0_1/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I"/usr/local/Cellar/r/3.2.0_1/R.framework/Versions/3.2/Resources/library/Rcpp/include"  -I/Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.7-x86_64-darwin-14/vendor/v8/include -fPIC  -g -O2  -c v8_typed_array.cpp -o v8_typed_array.o
v8_typed_array.cpp:105:18: error: no member named 'SetPointerInInternalField' in 'v8::Object'; did you mean 'SetAlignedPointerInInternalField'?
    args.This()->SetPointerInInternalField(0, buf);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~
                 SetAlignedPointerInInternalField
/Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.7-x86_64-darwin-14/vendor/v8/include/v8.h:1683:8: note: 'SetAlignedPointerInInternalField' declared here
  void SetAlignedPointerInInternalField(int index, void* value);
       ^
v8_typed_array.cpp:218:27: error: no member named 'GetPointerFromInternalField' in 'v8::Object'
      void* buf = buffer->GetPointerFromInternalField(0);
                  ~~~~~~  ^
v8_typed_array.cpp:231:27: error: no member named 'GetPointerFromInternalField' in 'v8::Object'
      void* buf = buffer->GetPointerFromInternalField(0);
                  ~~~~~~  ^
v8_typed_array.cpp:258:27: error: no member named 'GetPointerFromInternalField' in 'v8::Object'
      void* buf = buffer->GetPointerFromInternalField(0);
                  ~~~~~~  ^
4 errors generated.
make: *** [v8_typed_array.o] Error 1
ERROR: compilation failed for package ‘V8’
* removing ‘/usr/local/Cellar/r/3.2.0_1/R.framework/Versions/3.2/Resources/library/V8’

The downloaded source packages are in
	‘/private/var/folders/yj/r0b3fsmj3091ksvlygb1mbf00000gn/T/RtmpUj5xCi/downloaded_packages’
'/usr/local/Cellar/r/3.2.0_1/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  '/private/var/folders/yj/r0b3fsmj3091ksvlygb1mbf00000gn/T/RtmpUj5xCi/devtools4de66b359b54/ropensci-lawn-9b62a76'  \
  --library='/usr/local/Cellar/r/3.2.0_1/R.framework/Versions/3.2/Resources/library'  \
  --install-tests 

ERROR: dependency ‘V8’ is not available for package ‘lawn’
* removing ‘/usr/local/Cellar/r/3.2.0_1/R.framework/Versions/3.2/Resources/library/lawn’
Error: Command failed (1)
In addition: Warning message:
In utils::install.packages(pkgs, repos = repos, type = type, ...,  :
  installation of package ‘V8’ had non-zero exit status

**Comment by sckott** [comment]
@jeroenooms have you seen this error?

**Comment by jeroenooms** [comment]
haven't seen this, probably incompatible version of libv8 from gem. @samuelleach does the binary package work?

```r
install.packages("V8")
```

**Comment by sckott** [comment]
@samuelleach `lawn` is on CRAN, so you can try to install from there as well

**Comment by samuelleach** [comment]
Thanks @jeroenooms. I found that I did need to perform

`sudo gem uninstall libv8`
`install.packages("V8")`

before

devtools::install_github("ropensci/lawn")

which now works.

@sckott Minor thing, I didn't realise `lawn` was on CRAN - I just followed the install instructions on the report README. Perhaps update the README?

**Comment by jhollist** [comment]
Thanks for pointing that out @samuelleach.  I made the change!

**Comment by sckott** [comment]
@samuelleach glad it works now :)
