### ISSUE TITLE
How to convert to sp classes?

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/lawn#47]
I've got my shiny new lawn installation (great work guys) and it works:

```
hg = lawn_hex_grid(c(-96,31,-84,40), 50, 'miles') 
```

Only issue now: how to convert this to an sp class?

Apologies if its obvious - I've just tried this so far, no joy:

```
hgsp <- as(hg, "SpatialPolygons")
```

**Comment by sckott** [comment]
Made slight change to `geojsonio`, so reinstall from there `devtools::install_github("ropensci/geojsonio")`, then

```r
hg <- lawn::lawn_hex_grid(c(-96,31,-84,40), 50, 'miles')
geojsonio::geojson_sp(jsonlite::toJSON(unclass(hg), auto_unbox = TRUE))
```

**Comment by Robinlovelace** [comment]
Fantastic to see it working, many thanks. I imagine it would be useful to have a function such as `featurecollection_sp` or maybe `lawn_sp` in the lawn package that does just that. I can give implementing that a bash. Sound like a plan? As an aside, for your GIS work do you use sp classes or keep objects in other classes?

**Comment by sckott** [comment]
Hmm, 

> As an aside, for your GIS work do you use sp classes or keep objects in other classes?

I don't do a ton of GIS stuff, i'm guessing you do lots more :)  I do prefer geojson though since it's portable and thus easier to work with across R/other programming languages/web/etc.

**Comment by sckott** [comment]
i guess shape files are portable as well :)

**Comment by sckott** [comment]
we do already have `geojsonio` in `Enhances` https://github.com/ropensci/lawn/blob/master/DESCRIPTION#L32 - so can include examples using `geojsonio` for converting to spatial classes

**Comment by Robinlovelace** [comment]
Great reply - I consider this issue closed. Final follow up will be to add an example as you say. Where you you suggest adding an example of this class conversion? Vignette or example? Point me in the right direction and I can add something if you like.

**Comment by sckott** [comment]
Thanks to you for bringing this up!

If you have time, add eg's in 

* https://github.com/ropensci/lawn/blob/master/vignettes/lawn_vignette.Rmd
* https://github.com/ropensci/lawn/blob/master/README.Rmd
