### ISSUE TITLE
Update to v3.4.1

### ISSUE THREAD

**Issue by sckott** [ropensci/lawn#49]
https://github.com/Turfjs/turf/blob/master/CHANGELOG.md#301

**Comment by sckott** [comment]
most recent release https://github.com/Turfjs/turf/releases/tag/v3.0.11

**Comment by sckott** [comment]
methods that are no longer in new version of `lawn`:

* `lawn_average`
* `lawn_deviation`
* `lawn_count`
* `lawn_filter`
* `lawn_max`
* `lawn_median`
* `lawn_min`
* `lawn_sum`
* `lawn_variance`

`lawn_jenks` needs extra work to get to work again, see note within https://github.com/Turfjs/turf/blob/master/CHANGELOG.md#301

`lawn_quantile` needs extra work to get to work again, see note within https://github.com/Turfjs/turf/blob/master/CHANGELOG.md#301

remove `lawn_reclass` - its depredated in turf https://github.com/Turfjs/turf/issues/306

remove `lawn_size` - its depredated in turf https://github.com/Turfjs/turf/issues/306

**Comment by sckott** [comment]
hey @jhollist - sorry about the delay, got most things working, some things left to think about

note the work is on branch `turf-v3`, not on master

* `lawn_jenks` - should we keep this? we'd have to write the js from scratch, test commented out for now
* `lawn_quantile` - should we keep this? we'd have to write the js from scratch, test commented out for now
* `lawn_aggregate` - a new method `collect` http://turfjs.org/docs/#collect was introduced, i think to replace aggregate in part at least, now aggregate is gone from turf. should we just make this method defunct?
* should we add a function for the new method http://turfjs.org/docs/#collect ?

**Comment by jhollist** [comment]
My gut reaction is to have lawn mirror the current version of turf as closely as possible.  Thus we could drop `lawn_jenks` and `lawn_quantile`, and replace `lawn aggregate` with a lawn version of collect.  

Haven't looked at the other methods yet.  Won't have much time next couple of weeks.  Sorry.

**Comment by sckott** [comment]
Okay, and easier to just drop those too. those meta and assertions methods may push off until some later point if I can't sort out where they are

**Comment by jhollist** [comment]
Sounds good.  

As far as submission to JOSS, I hope to work on that soon.  Some potential confusion around licensing that EPA hasn't thought about it.  If I don't get clarification in a timely fashion, I'll just ignore the issue and work up the submission.

**Comment by sckott** [comment]
Okay

**Comment by sckott** [comment]
moved methods not found in current turf release to new issue for next milestone https://github.com/ropensci/lawn/issues/51
