### ISSUE TITLE
bind the new 'turf.circle' feature

### ISSUE THREAD

**Issue by mikejacktzen** [ropensci/lawn#50]
Looks like turf added the 'circle' feature
https://github.com/Turfjs/turf/tree/master/packages/turf-circle

which was highly requested
https://github.com/Turfjs/turf/issues/301

lawn should implement it's wrapper.

Since many web apis typically ask for a 'radius' disk
This would be useful for a lot of data analysis applications

**Comment by sckott** [comment]
thanks for the note - working on integrating new turf in this branch https://github.com/ropensci/lawn/tree/turf-v3 - will include

**Comment by sckott** [comment]
@mikejacktzen finally, we are now on turf `v3.5.1`, and  circle is in the pkg, install like `devtools::install_github("ropensci/lawn@turf-v3")`

some fxns don't work as there's still confusion on my part where some things have gone with new turf version.

**Comment by mikejacktzen** [comment]
@sckott Thanks for your hard work.

I got a chance to test the v3 updates.

I have a lingering question that motivated this issue/feature request for lawn_circle

My whole end goal was to get a resulting list of centers of 10-radii mile circles
that are generated from a starting list of initial hexagons with the same user-specified hex centroids.


1. user specifies extent
2. user gets a tesselation of hexagons (user specifies diameter of hexagon)
3. use resulting hexagons to get each hex centroids
4. use each centroid as centers for circles (user specifies diameter of circles)

Do you have any advice on the syntax and in/out to get to the final circles?
I believe this is just me not using the lawn syntax correct.

A short code below runs succesfuly up to the centroids of hexagon grids

```
############
# extent
############
minx=-118.521;miny=33.715;
maxx=-118.145;maxy=34.179;
extent_choose = c(minx,miny,maxx,maxy)

############
# hex grid
############
hex_grid = lawn_hex_grid(extent_choose, 10, 'miles')

############
# hex centroids
############
test = as_feature(hex_grid) %>% 
  purrr::map(lawn_centroid) 

test %>% view
str(test)
# List of 18
# $ :List of 3
# ..$ type      : chr "Feature"
# ..$ properties: Named list()
# ..$ geometry  :List of 2
# .. ..$ type       : chr "Point"
# .. ..$ coordinates: num [1:2] -118.5 33.7
# ..- attr(*, "class")= chr "point"
```

Where I'm confused is the next step on getting the centroids to points to circles
None of these brute force syntax combinations work
```
test %>% lawn_circle(center=.,radius = 10, steps = 100)
# Error: No method asJSON S3 class: point

test %>% 
  lawn_point()

test %>% 
  as_feature()
  purrr::map(lawn_point)
# Error in as_function(.f, ...) : argument ".f" is missing, with no default

```

**Comment by sckott** [comment]
@mikejacktzen i'll have a look, thanks for the examples

**Comment by sckott** [comment]
sorry, haven't forgotten about this, looking at this now

**Comment by sckott** [comment]
@mikejacktzen theres a smalll fix I did, reinstall, `devtools::install_github("ropensci/lawn")`

try

```r
library(lawn)
minx=-118.521;miny=33.715;
maxx=-118.145;maxy=34.179;
extent_choose = c(minx,miny,maxx,maxy)
hex_grid = lawn_hex_grid(extent_choose, 10, 'miles')
test <- as_feature(hex_grid) %>% purrr::map(lawn_centroid) 
test %>% purrr::map(lawn_circle, radius = 5) %>% view
```

<img width="866" alt="screen shot 2016-11-22 at 11 00 43 pm" src="https://cloud.githubusercontent.com/assets/577668/20553215/8507e7d6-b107-11e6-813e-c4ba6b267ea3.png">

**Comment by sckott** [comment]
@mikejacktzen let me know if that works or doesn't for you

**Comment by mikejacktzen** [comment]
@sckott your great updates definitely do the trick! 

I changed the radius in your last demo line to

``` test %>% purrr::map(lawn_circle, radius = 10) %>% view ```

and the resulting circles are exactly in agreement with the initial radius 10 hexagons

**Comment by sckott** [comment]
Great, glad it works
