### ISSUE TITLE
JOSS Submission

### ISSUE THREAD

**Issue by jhollist** [ropensci/lawn#59]
@sckott I am really close (finally) to submitting lawn to JOSS.  I'm gonna do a last read through on things tomorrow and then submit.  

You want to take another look or are you good with me submitting when ready?

**Comment by sckott** [comment]
where's the lastest version of it?

**Comment by jhollist** [comment]
On master here.

**Comment by sckott** [comment]
LGTM

**Comment by jhollist** [comment]
I had to look up LGTM! 

Should hopefully have this submitted tomorrow.

**Comment by sckott** [comment]
thanks for doing this

**Comment by jhollist** [comment]
Submitted to JOSS!

http://joss.theoj.org/papers/59d52acbbc08c98c90270f5b58e74067
