### ISSUE TITLE
Zenodo DOI

### ISSUE THREAD

**Issue by jhollist** [ropensci/lawn#61]
@sckott Heard back from @arfon on https://github.com/openjournals/joss-reviews/issues/194.  We need to link to Zenodo and push a release to get our DOI.  Since I don't have admin rights, can you take care of that?  Once the DOI is set I'll get everything else finalized.

**Comment by sckott** [comment]
sure, should the release be tied to a cran release or just tag it wherever it's at right now?

**Comment by jhollist** [comment]
That is a good question.  @arfon, any insights?  I'm thinking we can do a release for JOSS at the current version?

**Comment by arfon** [comment]
> That is a good question. @arfon, any insights? I'm thinking we can do a release for JOSS at the current version?

Ideally it should be the same version as was submitted to JOSS (Version: `v0.3.1`).

**Comment by jhollist** [comment]
OK.  

So we had another commit that bumped the version since I submitted the repository to JOSS.  Can we edit the submission to match the current version 0.3.2 (minus the dev version) and then release that?

**Comment by arfon** [comment]
👍 yep, that works

**Comment by sckott** [comment]
@jhollist  here's the markdown `[![DOI](https://zenodo.org/badge/31631259.svg)](https://zenodo.org/badge/latestdoi/31631259)`

**Comment by jhollist** [comment]
I'm out of the office this afternoon but will finalize all of this tomorrow.  Thanks @sckott and @arfon !

**Comment by jhollist** [comment]
And looks like we are good to go!  Thanks @arfon for the quick review.  

The link: <http://dx.doi.org/10.21105/joss.00194>

**Comment by sckott** [comment]
thanks @jhollist
