### ISSUE TITLE
Export `lawn` objects

### ISSUE THREAD

**Issue by michaeldorman** [ropensci/lawn#80]
Is there a way to convert a `lawn` GeoJSON object to an ordinary GeoJSON string? Or to convert it to any other type of spatial object to continue processing with non-`lawn` functions, such as to an `sf` object?

For instance, the following example (from documentation) creates a TIN object named `tin` - 
```r
library(lawn)
pts = lawn_random(bbox = c(-70, 40, -60, 60)) 
tin = lawn_tin(pts) 
## tin <FeatureCollection>   
## Bounding box: -67.4 41.2 -60.2 58.5   
## No. features: 11   
## No. points: 88   
## Properties: NULL
```

Is there a way to export the `tin` object to a GeoJSON file, or convert it to an `sf` object?

**Comment by sckott** [comment]
you could convert like 

```r
library(geojsonio)
geojson_sf(structure(tin, class="geo_list"))
```

**Comment by michaeldorman** [comment]
It works, thanks for the quick reply!

**Comment by sckott** [comment]
glad it works. 

curious, what do you use `lawn` for? thinking i don't see much use and maybe abandon the pkg, but do you find it useful?

**Comment by michaeldorman** [comment]
I needed to calculate a TIN layer, and a quick Google search pointed at `lawn`. If you know of other options to calculate a TIN layer will be happy to hear :-)

By the way, to go from an `sf` layer to a `lawn` object I wrote a temporary GeoJSON file on disk then read it back with `readLines` to get the GeoJSON string... Surely there is a less awkward way to go from `sf` to `lawn`, will be happy to hear any suggestion from your experience - 
```
filename = tempfile()
filename = paste0(filename, ".geojson")
st_write(dat %>% st_geometry, filename, delete_dsn = TRUE)
tmp = readLines(filename)
tmp = paste0(tmp, collapse = "")
tmp = as.feature(tmp)
```

**Comment by michaeldorman** [comment]
The package looks very useful, because turf.js has some functions not available elsewhere in R. But perhaps it will be more useful if it operated on standard spatial objects, such as `sf` layers, instead of a specific GeoJSON class.

**Comment by sckott** [comment]
I don't know of other TIN options. 

maybe something like this:

```r
library(sf)
library(lawn)
library(geojsonio)
p1 <- rbind(c(0,0), c(1,0), c(3,2), c(2,4), c(1,4), c(0,0))
p2 <- rbind(c(1,1), c(1,2), c(2,2), c(1,1))
pol <- sf::st_polygon(list(p1,p2))
polgeo <- geojsonio::geojson_json(pol)
x <- lawn::as.feature(unclass(polgeo))
lawn::lawn_area(x)
```


@jhollist what do you think jeff, have lawn take and output sf objects in addition to geojson?  maybe that would give this pkg more appeal?

**Comment by jhollist** [comment]
I think that would certainly increase its appeal.  Working in geojson makes sense given that is more native for Turf.js, but allowing sf for more direct I/O would be good.  So 👍 

I also looked around a bit, and TINs may also be possible from `rgeos::gDelaunayTriangulation`.  Also TIN is a simple features specification, but I don't think it has been implemented in `sf` yet.  Might be worth pinging the rspatial crew to see if any plans in the works.

**Comment by sckott** [comment]
> but allowing sf for more direct I/O would be good

if we do it though, i guess it makes sense to have it supported in every lawn fxn, but then again users would just use the sf version if there is an equivalent thing in sf as it'd probably be faster. - so not sure ...

**Comment by michaeldorman** [comment]
Thank you very much for the guidance! I understand now how to convert to and from GeoJSON/`lawn` objects. 

Going through the vignette and docs I was looking for `as_lawn` and `as_sf` functions, or something equivalent, for easier interface with `sf`. Moreover, if the functions in `lawn` could internally make these kind of transformations, accepting either `lawn` or `sf` objects as arguments, I think this would greatly improve usability. 

TIN and other rarely-used simple feature types are implemented in `sf`, but seems like there are no functions using these implementations yet - 
```
> st_as_sfc("TIN (((0 0 0, 0 0 1, 0 1 0, 0 0 0)), ((0 0 0, 0 1 0, 1 1 0, 0 0 0)))")
Geometry set for 1 feature 
geometry type:  TIN
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 1 ymax: 1
epsg (SRID):    NA
proj4string:    NA
TIN (((0 0 0, 0 0 1, 0 1 0, 0 0 0)), ((0 0 0, 0...
```

**Comment by jhollist** [comment]
> > but allowing sf for more direct I/O would be good
> 
> if we do it though, i guess it makes sense to have it supported in every lawn fxn, but then again users would just use the sf version if there is an equivalent thing in sf as it'd probably be faster. - so not sure ...

Agreed that it should be for all lawn functions.  The other issue you raise is a different discussion!  How much sense does it make to continue with lawn when other packages provide similar/same functionality and may be more standardized in the R universe and/or are faster...  Would be interesting to see a comparison of functionality across the geospatial packages and what packages can do what, how long that takes, etc.  But again, a different issue.

**Comment by sckott** [comment]
@michaeldorman 

- We'll look into adding fxns for coercing to/from `sf` https://github.com/ropensci/lawn/issues/81
- having every fxn accept sf objects is more work, but we'll look into it https://github.com/ropensci/lawn/issues/82

**Comment by sckott** [comment]
@jhollist one idea is maybe we merge lawn and https://github.com/ropensci/geoops/ , using the lawn fxns where there isn't a geoops version. basically i've reimplemented the JS turf.js methods in c++. i have done benchmarks against rgeos, but not lawn https://github.com/ropensci/geoops/#comparison-to-rgeos - i sorta shy away from merging though cause part of the downside of lawn is that V8 can cause a install headache on some linux OS'es

**Comment by jhollist** [comment]
Think I share your hesitation on the merge, but if you reimplement in c++ all the Turf.js functionality that would be good.  I can also see a use case for geoops as opposed to sf for those that want to work directly on geoJSON but also in those cases where getting the sf (and rgdal, rgeos, sp) dependencies installed is a pain.  For example, I've been trying to get shiny apps up and running on EPA's cloud.gov org.  For the most part it is fine, but the gdal dependency has been a problem.  If I had a dependency free option, like geoops, that would be nice.  Not sure if it could be a 1:1 replacement for sf (a tall order!) nor if that is even desirable, but in some cases it really could alleviate dependency headaches.

**Comment by sckott** [comment]
yeah, that's my thinking is for some people the installation problems vs. performance tradeoff will be worth it. only dealing with geojson makes it simpler of course, but less flexible as you have to input and output geojson. been stuck on some of the turf.js stuff that's hard for me to convert to c++ 🕙
