### ISSUE TITLE
Move readme images into man/figures

### ISSUE THREAD

**Issue by jeroen** [ropensci/lawn#83]
See https://docs.ropensci.org/lawn/ and this comment from Hadley: https://github.com/ropensci/rotemplate/issues/19#issuecomment-506315565

You can also have a look where other packages store `readme.md` figures:

 - https://github.com/ropensci/tidyhydat/
 - https://github.com/ropensci/drake/

**Comment by sckott** [comment]
done in 74de7ffa232f74be223cb09209ea4ec963483a05
